// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-nunu/nunu-layout-advanced/internal/handler"
	"github.com/go-nunu/nunu-layout-advanced/internal/job"
	"github.com/go-nunu/nunu-layout-advanced/internal/repository"
	"github.com/go-nunu/nunu-layout-advanced/internal/router"
	"github.com/go-nunu/nunu-layout-advanced/internal/server"
	"github.com/go-nunu/nunu-layout-advanced/internal/service"
	"github.com/go-nunu/nunu-layout-advanced/pkg/app"
	"github.com/go-nunu/nunu-layout-advanced/pkg/jwt"
	"github.com/go-nunu/nunu-layout-advanced/pkg/log"
	"github.com/go-nunu/nunu-layout-advanced/pkg/server/http"
	"github.com/go-nunu/nunu-layout-advanced/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	jobRepository := repository.NewJobRepository(repositoryRepository)
	jobService := service.NewJobService(serviceService, jobRepository)
	payService := service.NewPayService(viperViper)
	orderRepository := repository.NewOrderRepository(repositoryRepository)
	orderItemRepository := repository.NewOrderItemRepository(repositoryRepository)
	contactVoucherHistoryRepository := repository.NewContactVoucherHistoryRepository(repositoryRepository)
	orderService := service.NewOrderService(serviceService, orderRepository, orderItemRepository, jobRepository, userRepository, contactVoucherHistoryRepository)
	jobHandler := handler.NewJobHandler(handlerHandler, jobService, orderService, payService)
	collectRepository := repository.NewCollectRepository(repositoryRepository)
	collectService := service.NewCollectService(serviceService, collectRepository, jobRepository)
	collectHandler := handler.NewCollectHandler(handlerHandler, collectService)
	contactHistoryRepository := repository.NewContactHistoryRepository(repositoryRepository)
	contactHistoryService := service.NewContactHistoryService(serviceService, contactHistoryRepository, jobRepository, userRepository)
	contactHistoryHandler := handler.NewContactHistoryHandler(handlerHandler, contactHistoryService)
	contactVoucherHistoryService := service.NewContactVoucherHistoryService(serviceService, contactVoucherHistoryRepository, userRepository)
	contactVoucherHistoryHandler := handler.NewContactVoucherHistoryHandler(handlerHandler, contactVoucherHistoryService, orderService, contactHistoryService, payService)
	wechatService := service.NewWechatService(logger, viperViper, jwtJWT, userRepository)
	wechatHandler := handler.NewWechatHandler(handlerHandler, orderService, wechatService)
	uploadService := service.NewUploadService(viperViper)
	uploadHandler := handler.NewUploadHandler(handlerHandler, uploadService)
	routerDeps := router.RouterDeps{
		Logger:                       logger,
		Config:                       viperViper,
		JWT:                          jwtJWT,
		UserHandler:                  userHandler,
		JobHandler:                   jobHandler,
		CollectHandler:               collectHandler,
		ContactHistoryHandler:        contactHistoryHandler,
		ContactVoucherHistoryHandler: contactVoucherHistoryHandler,
		WechatHandler:                wechatHandler,
		UploadHandler:                uploadHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewJobRepository, repository.NewCollectRepository, repository.NewContactHistoryRepository, repository.NewOrderRepository, repository.NewOrderItemRepository, repository.NewContactVoucherHistoryRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewJobService, service.NewCollectService, service.NewContactHistoryService, service.NewOrderService, service.NewOrderItemService, service.NewContactVoucherHistoryService, service.NewWechatService, service.NewUploadService, service.NewPayService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewJobHandler, handler.NewCollectHandler, handler.NewContactHistoryHandler, handler.NewContactVoucherHistoryHandler, handler.NewWechatHandler, handler.NewUploadHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
