// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	model "github.com/go-nunu/nunu-layout-advanced/internal/model"
	service "github.com/go-nunu/nunu-layout-advanced/internal/service"
	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetInfo mocks base method.
func (m *MockUserService) GetInfo(ctx context.Context, userID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockUserServiceMockRecorder) GetInfo(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockUserService)(nil).GetInfo), ctx, userID)
}

// ListInvites mocks base method.
func (m *MockUserService) ListInvites(ctx context.Context, userID int64, pageNum, pageSize int) ([]*model.User, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvites", ctx, userID, pageNum, pageSize)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListInvites indicates an expected call of ListInvites.
func (mr *MockUserServiceMockRecorder) ListInvites(ctx, userID, pageNum, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvites", reflect.TypeOf((*MockUserService)(nil).ListInvites), ctx, userID, pageNum, pageSize)
}

// UpdateGeo mocks base method.
func (m *MockUserService) UpdateGeo(ctx context.Context, userID int64, input service.UpdateUserGeoInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGeo", ctx, userID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGeo indicates an expected call of UpdateGeo.
func (mr *MockUserServiceMockRecorder) UpdateGeo(ctx, userID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGeo", reflect.TypeOf((*MockUserService)(nil).UpdateGeo), ctx, userID, input)
}

// UpdateInfo mocks base method.
func (m *MockUserService) UpdateInfo(ctx context.Context, userID int64, input service.UpdateUserInfoInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInfo", ctx, userID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInfo indicates an expected call of UpdateInfo.
func (mr *MockUserServiceMockRecorder) UpdateInfo(ctx, userID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInfo", reflect.TypeOf((*MockUserService)(nil).UpdateInfo), ctx, userID, input)
}
